eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9093/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: microservice-user
          uri: lb://microserviceuser
          predicates:
            - Path=/utilisateur/**
          filters:
            - RewritePath=/utilisateur/(?<path>.*), /$\{path}
        
        - id: microservice-projet
          uri: lb://microserviceprojet
          predicates:
            - Path=/projet/**
          filters:
            - RewritePath=/projet/(?<path>.*), /$\{path}
